#!/usr/bin/env bash
# echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo chmod 777 /etc/nginx/ /etc/nginx/nginx.conf
sudo sed -i '/sendfile on;/ a add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx restart
sudo service nginx reload
