#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo chmod 777 /var/www/html/index.nginx-debian.html
sudo sed -i "12i add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
