#!/usr/bin/env bash
#To file, or not to file

FILE="School"
if [ -e "$FILE" ]
then
    echo "school file exists"
    if [ ! -s "$FILE" ]
    then
        echo "$FILE is empty"
    else 
        echo "$FILE is not empty"
    fi
    if [ -f "$FILE" ]
    then  
        echo "$FILE is a regular file"
    fi
else
    echo "$FILE file does not exist"
fi
