#!/usr/bin/env bash
#To file, or not to file

FILE="School"

if [ -e "$FILE" ]
then
    echo "school file exists"
    if [ ! -s "$FILW" ]
    then
        echo "school is empty"
    else 
        echo "school is not empty"
    fi
    if [ -f "$FILE" ]
    then  
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
